# Site settings
title: Austin Pray
site_title: Austin Pray Â· Full Stack Developer in Dallas, TX
byline: writes software for the web.
email: austin@austinpray.com
description: > # this means to ignore newlines until "baseurl:"
  Austin is a full stack developer focused on pushing the limits of the web as
  a platform for rich interactive experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://austinpray.com" # the base hostname & protocol for your site
github_username:  austinpray
#stackoverflow: "https://stackoverflow.com/users/1585343/austin-pray"

repo_baseurl: "https://github.com/austinpray/austinpray.com/blob/gh-pages/"
repo_editurl: "https://github.com/austinpray/austinpray.com/edit/gh-pages/"

# Build settings
markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope: 
      path: ""
      type: posts
    values:
      layout: post
      author: "Austin Pray"

exclude:
  - .editorconfig
  - .gitignore
  - .idea
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
  - _projects
  - vendor

plugins:
  - jekyll-redirect-from
