# Site settings
title: Austin Pray
site_title: Austin Pray Â· Full Stack Developer in Dallas, TX
byline: writes software for the web.
email: austin@austinpray.com
description: > # this means to ignore newlines until "baseurl:"
  Austin is a full stack developer focused on pushing the limits of the web as
  a platform for rich interactive experiences. He is the principal and lead
  developer at corelaunch.com, a small consulting shop that builds software for
  the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://austinpray.com" # the base hostname & protocol for your site
twitter_username: austinpray
github_username:  austinpray
gplus_username: +AustinPray
stackoverflow: "https://stackoverflow.com/users/1585343/austin-pray"

repo_baseurl: "https://github.com/austinpray/austinpray.com/blob/gh-pages/"
repo_editurl: "https://github.com/austinpray/austinpray.com/edit/gh-pages/"

# Build settings
markdown: kramdown

defaults:
  -
    scope: 
      path: ""
      type: posts
    values:
      layout: post
      author: "Austin Pray"

gems:
  - jekyll-sitemap

scripts: 
  d3: "//cdn.jsdelivr.net/d3js/3.5.3/d3.js"
  lodash: "//cdn.jsdelivr.net/lodash/3.0.0/lodash.js"
  activity: "/scripts/activity.js"
